name: Test

on:
  pull_request:
    types: [ labeled, synchronize]

jobs:
  RunLabel:
    # if: ${{ github.event.pull_request.labels.name == 'benchmark' || github.event.label.name == 'benchmark' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check object
        run: |
          cat << OBJECT
          ${{ toJson(github) }}
          OBJECT
