name: Test

on:
  pull_request:
    types:
      - "labeled"
      - "synchronize"

jobs:
  RunLabel:
    if: ${{ github.event.label.name == 'benchmark' }}
    runs-on: ubuntu-latest
    steps:
      - run:  echo "Hello World"
      - run: echo "Testing actions"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
