name: Lint

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  git:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
        with:
          fetch-depth: '3'
      - run: git rev-parse HEAD
      - run: git rev-parse HEAD^
