name: Test

on:
  pull_request:
    types:
      - "labeled"
      - "synchronize"

jobs:
  RunLabel:
    if: ${{ github.event.labels.name == 'benchmark' }}
    runs-on: ubuntu-latest
    steps:
      - run:  echo "Hello World"
